"""add_student_answer_and_review_status

Revision ID: 46eb66e6d64d
Revises: 29efa4114f28
Create Date: 2026-01-19 15:36:57.209648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46eb66e6d64d'
down_revision: Union[str, Sequence[str], None] = '29efa4114f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('student_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'student_answer')
    # ### end Alembic commands ###
