"""Add attempts to tasks

Revision ID: 7ba266c11b1a
Revises: 99442b518aa3
Create Date: 2026-01-19 13:10:11.462800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba266c11b1a'
down_revision: Union[str, Sequence[str], None] = '99442b518aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('task_data', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attempts')
    op.drop_column('tasks', 'task_data')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
